export const UPDATE_USERS_FROM_ONE = 'UPDATE_USERS_FROM_ONE';
export const GET_EXECUTION_DETAIL = 'GET_EXECUTION_DETAIL';
export const UPDATE_NOAH_LIST = 'UPDATE_NOAH_LIST';
export const UPDATE_NOAH_DETAIL = 'UPDATE_NOAH_DETAIL';
export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST';
export const UPDATE_DISK_SPACE_INFO = 'UPDATE_DISK_SPACE_INFO';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

