export const GET_USERS_FROM_ONE = Symbol('GET_USERS_FROM_ONE');
export const GET_EXECUTION_DETAIL = Symbol('GET_EXECUTION_DETAIL');
export const UPDATE_NOAH_LIST = Symbol('UPDATE_NOAH_LIST');
export const UPDATE_NOAH_DETAIL = Symbol('UPDATE_NOAH_DETAIL');
export const UPDATE_CATEGORY_LIST = Symbol('UPDATE_CATEGORY_LIST');
export const UPDATE_DISK_SPACE_INFO = Symbol('UPDATE_DISK_SPACE_INFO');

