// 临时文件  dev.gitee.work

export const agents = [
    {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t c832cf3b-19d7-4075-b824-b4d2a8c15786 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t c832cf3b-19d7-4075-b824-b4d2a8c15786',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'c832cf3b-19d7-4075-b824-b4d2a8c15786',
        'createTime': '2022-01-26 11:18:17',
        'name': 'IDE-740ad7f006914faf82c6a85ec1a481fc',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 7317454c-bacb-4102-93b3-72791e5b176a >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 7317454c-bacb-4102-93b3-72791e5b176a',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '7317454c-bacb-4102-93b3-72791e5b176a',
        'createTime': '2022-01-24 10:51:19',
        'name': 'IDE-dada89b38c7444ec80009f17ae7b6025',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 2df71c62-58ef-4a8f-a346-02336fe7bada >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 2df71c62-58ef-4a8f-a346-02336fe7bada',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '2df71c62-58ef-4a8f-a346-02336fe7bada',
        'createTime': '2022-01-18 17:05:56',
        'name': 'IDE-e86147e25a5f49fba3587ae4fbba3dce',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 9c7df428-5255-4691-b4e6-5355d84f0748 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 9c7df428-5255-4691-b4e6-5355d84f0748',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '9c7df428-5255-4691-b4e6-5355d84f0748',
        'createTime': '2022-01-10 17:00:26',
        'name': 'IDE-ff4b6388c0ba4299b1b0c96c26c068d8',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 1aff0476-ad66-48aa-a9b2-32dcc592ef63 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 1aff0476-ad66-48aa-a9b2-32dcc592ef63',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '1aff0476-ad66-48aa-a9b2-32dcc592ef63',
        'createTime': '2022-01-10 16:27:13',
        'name': 'IDE-c5cacf0930004ddbad73afbe12d7418b',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 276ba9a6-a27c-477d-8696-022ad3b0b7c3 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 276ba9a6-a27c-477d-8696-022ad3b0b7c3',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '276ba9a6-a27c-477d-8696-022ad3b0b7c3',
        'createTime': '2022-01-10 13:09:39',
        'name': 'IDE-260dbee411dc45cda2e341958a5022a3',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 1f9431f9-e11b-4d7d-b6ce-1d6fa9e773e9 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 1f9431f9-e11b-4d7d-b6ce-1d6fa9e773e9',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '1f9431f9-e11b-4d7d-b6ce-1d6fa9e773e9',
        'createTime': '2022-01-10 12:59:51',
        'name': 'IDE-98e646fd490b41d3b93f42fd2277e134',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 46111659-5cc3-46bc-909c-1971a7991888 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 46111659-5cc3-46bc-909c-1971a7991888',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '46111659-5cc3-46bc-909c-1971a7991888',
        'createTime': '2022-01-10 09:27:49',
        'name': 'IDE-64bfde61ed8345eebb0e773ca56d3f0b',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 573c3deb-7b81-490b-9993-aed8b26b8f53 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 573c3deb-7b81-490b-9993-aed8b26b8f53',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '573c3deb-7b81-490b-9993-aed8b26b8f53',
        'createTime': '2022-01-07 23:58:52',
        'name': 'IDE-47975bcf1ae44a638169fa108b044ef4',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t be569340-9432-4aba-89ae-e462754d16df >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t be569340-9432-4aba-89ae-e462754d16df',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'be569340-9432-4aba-89ae-e462754d16df',
        'createTime': '2022-01-05 17:22:40',
        'name': 'IDE-69bbdc0994e946b1994e1d5d2004bb4a',
    }, {
        'labelId': 161,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 5e1b7e4d-9ab8-4ae5-9b08-96be0fe80bab >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 5e1b7e4d-9ab8-4ae5-9b08-96be0fe80bab',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'INSTALLING',
        'note': '',
        'hiGroup': null,
        'executorCount': 22,
        'sendEmail': null,
        'type': 2,
        'uuid': '5e1b7e4d-9ab8-4ae5-9b08-96be0fe80bab',
        'createTime': '2021-12-14 21:04:01',
        'name': 'cqtest006',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t a2c1e28a-3510-4767-8386-49f7031ddddf >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t a2c1e28a-3510-4767-8386-49f7031ddddf',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'a2c1e28a-3510-4767-8386-49f7031ddddf',
        'createTime': '2021-12-14 14:48:51',
        'name': 'IDE-b784b9127e314fe086da6d3e66d9f2de',
    }, {
        'labelId': 161,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t c37d75db-f532-4199-9d76-543698d87281 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t c37d75db-f532-4199-9d76-543698d87281',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'test1111111111',
        'hiGroup': null,
        'executorCount': 2,
        'sendEmail': null,
        'type': 2,
        'uuid': 'c37d75db-f532-4199-9d76-543698d87281',
        'createTime': '2021-12-07 17:41:15',
        'name': 'test1111111111',
    }, {
        'labelId': 161,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 4e4ff1ee-f119-4c99-a40b-b632c730824b >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 4e4ff1ee-f119-4c99-a40b-b632c730824b',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '4e4ff1ee-f119-4c99-a40b-b632c730824b',
        'createTime': '2021-12-07 15:54:25',
        'name': 'test001',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t fc86d9b8-bb4d-4e1a-b300-030f1c7e6982 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t fc86d9b8-bb4d-4e1a-b300-030f1c7e6982',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'fc86d9b8-bb4d-4e1a-b300-030f1c7e6982',
        'createTime': '2021-12-06 15:13:38',
        'name': 'IDE-1f3a7b8cec2e40108a16c21b0ec85670',
    }, {
        'labelId': 161,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 0302b01f-4f76-4b75-9f97-80072a3e423c >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 0302b01f-4f76-4b75-9f97-80072a3e423c',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '0302b01f-4f76-4b75-9f97-80072a3e423c',
        'createTime': '2021-12-03 19:39:42',
        'name': '136',
    }, {
        'labelId': 161,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8a660eb0-9514-47ee-8e5c-d88d5fb73914 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8a660eb0-9514-47ee-8e5c-d88d5fb73914',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '8a660eb0-9514-47ee-8e5c-d88d5fb73914',
        'createTime': '2021-11-26 14:35:27',
        'name': 'cqtest10',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 303a4c4f-6b85-4007-a381-5e3fc9af2740 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 303a4c4f-6b85-4007-a381-5e3fc9af2740',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '303a4c4f-6b85-4007-a381-5e3fc9af2740',
        'createTime': '2021-11-11 11:46:47',
        'name': 'IDE-ebf88a5d751741c995d7829464f2091a',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t dc48a0f3-2920-41e2-9eda-d2b0b3096748 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t dc48a0f3-2920-41e2-9eda-d2b0b3096748',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 1,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'dc48a0f3-2920-41e2-9eda-d2b0b3096748',
        'createTime': '2021-11-11 11:28:12',
        'name': 'IDE-238dabe072584bfc852f0afe0012c115',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 104d7cab-5d19-40a6-a2ab-74c09be0fbd4 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 104d7cab-5d19-40a6-a2ab-74c09be0fbd4',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '104d7cab-5d19-40a6-a2ab-74c09be0fbd4',
        'createTime': '2021-11-08 20:00:54',
        'name': 'IDE-08fe52a824be47c0be9bcdfa7ac49067',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 38fdea11-e423-4c52-b5ca-f0628ec77a9f >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 38fdea11-e423-4c52-b5ca-f0628ec77a9f',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '38fdea11-e423-4c52-b5ca-f0628ec77a9f',
        'createTime': '2021-11-08 13:12:05',
        'name': 'IDE-880c51026bf742a8aa4aacbfd3575549',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 6fb9c8c3-4da7-4d26-bedf-0e99c89187a9 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 6fb9c8c3-4da7-4d26-bedf-0e99c89187a9',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '6fb9c8c3-4da7-4d26-bedf-0e99c89187a9',
        'createTime': '2021-11-08 13:06:58',
        'name': 'IDE-597f1d3f6f6a4fc9826833fc62eab6dc',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 2d40c769-705b-4894-a32f-692f463c893f >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 2d40c769-705b-4894-a32f-692f463c893f',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 1,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '2d40c769-705b-4894-a32f-692f463c893f',
        'createTime': '2021-10-27 22:57:48',
        'name': 'IDE-d41e2c1ca447415199c115a73afb812c',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8ef64398-1f5b-4ba8-b5e5-cce9325808a2 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8ef64398-1f5b-4ba8-b5e5-cce9325808a2',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '8ef64398-1f5b-4ba8-b5e5-cce9325808a2',
        'createTime': '2021-10-27 11:18:26',
        'name': 'IDE-8d5dfbfea39b41faa04db0cffecce8c5',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t d4630172-e9fd-4491-b0d5-651c191c822e >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t d4630172-e9fd-4491-b0d5-651c191c822e',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'd4630172-e9fd-4491-b0d5-651c191c822e',
        'createTime': '2021-10-27 11:10:03',
        'name': 'IDE-912e9392551a4d1fb3fab9e63819784d',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 23d17000-8489-4646-9aba-f4f3b2248087 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 23d17000-8489-4646-9aba-f4f3b2248087',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '23d17000-8489-4646-9aba-f4f3b2248087',
        'createTime': '2021-10-27 11:08:56',
        'name': 'IDE-6a3f6ef7b1eb4cafad062e51926c84bc',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 7329ee8b-4ae9-46cb-99d5-3e70f3bc7617 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 7329ee8b-4ae9-46cb-99d5-3e70f3bc7617',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '7329ee8b-4ae9-46cb-99d5-3e70f3bc7617',
        'createTime': '2021-10-27 10:43:19',
        'name': 'IDE-175a513fc852474bac8ee906f9195d05',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t cf2c425f-6800-43ac-a7be-ec866cad7022 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t cf2c425f-6800-43ac-a7be-ec866cad7022',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'cf2c425f-6800-43ac-a7be-ec866cad7022',
        'createTime': '2021-10-12 11:38:42',
        'name': 'IDE-5d843c6b7d1f45f580d1314369939789',
    }, {
        'labelId': 99999,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 498218e6-082e-40b9-b6df-b2f11c08b815 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 498218e6-082e-40b9-b6df-b2f11c08b815',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '498218e6-082e-40b9-b6df-b2f11c08b815',
        'createTime': '2021-09-30 10:21:16',
        'name': 'IDE-6a157c98c05c409cad95282790ab9d8f',
    }, {
        'labelId': 161,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8cbb856d-9237-498c-87b8-c95c8dd23212 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8cbb856d-9237-498c-87b8-c95c8dd23212',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '2222211',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '8cbb856d-9237-498c-87b8-c95c8dd23212',
        'createTime': '2021-09-27 21:24:18',
        'name': '222222222',
    }, {
        'labelId': 103,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t aac367e7-9e41-4db3-b639-b89784627654 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t aac367e7-9e41-4db3-b639-b89784627654',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '1',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'aac367e7-9e41-4db3-b639-b89784627654',
        'createTime': '2021-09-25 23:05:57',
        'name': 'my',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t f3a71fbf-0fed-4e15-8a7b-de939fdba494 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t f3a71fbf-0fed-4e15-8a7b-de939fdba494',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'f3a71fbf-0fed-4e15-8a7b-de939fdba494',
        'createTime': '2021-09-06 07:14:52',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t ed3f99e8-0a59-4f09-9b48-2d439e460902 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t ed3f99e8-0a59-4f09-9b48-2d439e460902',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'ed3f99e8-0a59-4f09-9b48-2d439e460902',
        'createTime': '2021-09-02 08:08:55',
        'name': 'cloudIde',
    }, {
        'labelId': 107,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 3c7dd3e0-1313-44de-a872-91db022b88ba >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 3c7dd3e0-1313-44de-a872-91db022b88ba',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '测试机',
        'hiGroup': null,
        'executorCount': 3,
        'sendEmail': null,
        'type': 2,
        'uuid': '3c7dd3e0-1313-44de-a872-91db022b88ba',
        'createTime': '2021-08-30 09:19:55',
        'name': '后端研发测试机',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 4e1138dd-31bc-4914-982d-50e1857a2278 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 4e1138dd-31bc-4914-982d-50e1857a2278',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '4e1138dd-31bc-4914-982d-50e1857a2278',
        'createTime': '2021-08-25 11:15:57',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t d62e854f-60d5-4ff0-9ef2-a6c98fc879ba >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t d62e854f-60d5-4ff0-9ef2-a6c98fc879ba',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'd62e854f-60d5-4ff0-9ef2-a6c98fc879ba',
        'createTime': '2021-08-20 06:48:45',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 5d634819-8ad3-4087-86fa-8fdcbe614451 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 5d634819-8ad3-4087-86fa-8fdcbe614451',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '5d634819-8ad3-4087-86fa-8fdcbe614451',
        'createTime': '2021-08-19 03:39:16',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t a2ed1f92-2911-4f7e-9f5a-54b2437a6ebe >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t a2ed1f92-2911-4f7e-9f5a-54b2437a6ebe',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'a2ed1f92-2911-4f7e-9f5a-54b2437a6ebe',
        'createTime': '2021-08-18 06:06:24',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 9c4937fc-6041-4bca-8e0f-d029466d94d9 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 9c4937fc-6041-4bca-8e0f-d029466d94d9',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '9c4937fc-6041-4bca-8e0f-d029466d94d9',
        'createTime': '2021-08-17 03:23:56',
        'name': 'cloudIde',
    }, {
        'labelId': 103,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8db31a7d-5bfa-48f9-8887-b381542ec63a >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8db31a7d-5bfa-48f9-8887-b381542ec63a',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '2',
        'hiGroup': null,
        'executorCount': 2,
        'sendEmail': null,
        'type': 2,
        'uuid': '8db31a7d-5bfa-48f9-8887-b381542ec63a',
        'createTime': '2021-08-16 13:32:43',
        'name': 'ArmJira',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 6efad841-b9d3-48e3-8299-d1092bf95d6e >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 6efad841-b9d3-48e3-8299-d1092bf95d6e',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '6efad841-b9d3-48e3-8299-d1092bf95d6e',
        'createTime': '2021-08-13 09:03:26',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 0ba79c61-b130-4b4c-8159-4921c58302d0 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 0ba79c61-b130-4b4c-8159-4921c58302d0',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '0ba79c61-b130-4b4c-8159-4921c58302d0',
        'createTime': '2021-08-13 08:54:38',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 4b2a5f11-2c62-436f-abba-ab26525de505 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 4b2a5f11-2c62-436f-abba-ab26525de505',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '4b2a5f11-2c62-436f-abba-ab26525de505',
        'createTime': '2021-08-13 08:47:01',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t b9ae9dce-7c09-490c-9d9c-07099b5d912d >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t b9ae9dce-7c09-490c-9d9c-07099b5d912d',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'b9ae9dce-7c09-490c-9d9c-07099b5d912d',
        'createTime': '2021-08-10 12:19:16',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t d4e8e760-1d5c-4ea1-aac3-4555f05fa1d3 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t d4e8e760-1d5c-4ea1-aac3-4555f05fa1d3',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'd4e8e760-1d5c-4ea1-aac3-4555f05fa1d3',
        'createTime': '2021-08-10 06:50:38',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t d23fdc7b-abd6-43e9-a7db-5882dc330107 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t d23fdc7b-abd6-43e9-a7db-5882dc330107',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'd23fdc7b-abd6-43e9-a7db-5882dc330107',
        'createTime': '2021-08-10 05:39:16',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t b15ea407-637d-4d14-98a6-5a0fe58a77d7 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t b15ea407-637d-4d14-98a6-5a0fe58a77d7',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'b15ea407-637d-4d14-98a6-5a0fe58a77d7',
        'createTime': '2021-08-09 08:49:56',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t c1cc439a-2402-49ef-b4e2-5c542ee3c700 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t c1cc439a-2402-49ef-b4e2-5c542ee3c700',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'c1cc439a-2402-49ef-b4e2-5c542ee3c700',
        'createTime': '2021-07-28 09:24:25',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 94309b3c-fad2-4281-8007-c458bfd8e47c >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 94309b3c-fad2-4281-8007-c458bfd8e47c',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '94309b3c-fad2-4281-8007-c458bfd8e47c',
        'createTime': '2021-07-28 09:20:01',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8c11d0bf-cc2f-4474-a621-5543befd5c21 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8c11d0bf-cc2f-4474-a621-5543befd5c21',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '8c11d0bf-cc2f-4474-a621-5543befd5c21',
        'createTime': '2021-07-28 09:12:47',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t f683416c-cc1c-420f-9d16-6d201e6159c4 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t f683416c-cc1c-420f-9d16-6d201e6159c4',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'f683416c-cc1c-420f-9d16-6d201e6159c4',
        'createTime': '2021-07-28 09:07:29',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 28cf7933-1be0-41f7-a602-aa0d44aa2b6e >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 28cf7933-1be0-41f7-a602-aa0d44aa2b6e',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '28cf7933-1be0-41f7-a602-aa0d44aa2b6e',
        'createTime': '2021-07-28 08:33:04',
        'name': 'cloudIde',
    }, {
        'labelId': 1,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 9518c505-4480-472e-b869-58e067329bde >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 9518c505-4480-472e-b869-58e067329bde',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cloudIde',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '9518c505-4480-472e-b869-58e067329bde',
        'createTime': '2021-07-28 07:08:17',
        'name': 'cloudIde',
    }, {
        'labelId': 97,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 13f208d1-d565-4061-85fa-3efb06e2678c >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 13f208d1-d565-4061-85fa-3efb06e2678c',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '192.168.80.236 ',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '13f208d1-d565-4061-85fa-3efb06e2678c',
        'createTime': '2021-06-28 06:18:58',
        'name': 'Code对接PIPE临时过渡主机',
    }, {
        'labelId': 14,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 7b34d8a5-b248-4966-9986-e97a210156e1 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 7b34d8a5-b248-4966-9986-e97a210156e1',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'test',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '7b34d8a5-b248-4966-9986-e97a210156e1',
        'createTime': '2021-06-09 03:37:10',
        'name': 'test',
    }, {
        'labelId': 51,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 1e4b4f04-e548-4649-9680-d0c295157df1 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 1e4b4f04-e548-4649-9680-d0c295157df1',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'dev',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '1e4b4f04-e548-4649-9680-d0c295157df1',
        'createTime': '2021-03-26 12:38:48',
        'name': 'dev',
    }, {
        'labelId': 49,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t b8701345-2486-4f1c-9941-21f9662ea9a1 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t b8701345-2486-4f1c-9941-21f9662ea9a1',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'abab',
        'hiGroup': null,
        'executorCount': 5,
        'sendEmail': null,
        'type': 2,
        'uuid': 'b8701345-2486-4f1c-9941-21f9662ea9a1',
        'createTime': '2021-03-25 03:19:30',
        'name': '192_168_80_97',
    }, {
        'labelId': 45,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 86b633d1-3c1b-4362-a10f-94047d4bd0e1 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 86b633d1-3c1b-4362-a10f-94047d4bd0e1',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '发',
        'hiGroup': null,
        'executorCount': 5,
        'sendEmail': null,
        'type': 2,
        'uuid': '86b633d1-3c1b-4362-a10f-94047d4bd0e1',
        'createTime': '2021-03-08 06:36:11',
        'name': 'server_xhd_test-1',
    }, {
        'labelId': 40,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8809a811-195f-45fd-9bac-237abe904f25 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8809a811-195f-45fd-9bac-237abe904f25',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 17,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'ONLINE',
        'note': 'test',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '8809a811-195f-45fd-9bac-237abe904f25',
        'createTime': '2021-01-28 09:50:42',
        'name': 'test',
    }, {
        'labelId': 32,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 383a4237-4101-437e-8eb7-13a153581e3c >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 383a4237-4101-437e-8eb7-13a153581e3c',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': '36%',
        'memoryUsedRate': '75%',
        'status': 'ONLINE',
        'note': 'demo测试机\n',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': '383a4237-4101-437e-8eb7-13a153581e3c',
        'createTime': '2021-01-12 06:17:01',
        'name': '192.168.80.97',
    }, {
        'labelId': 28,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 56c85143-19cd-46b0-b9e5-1ba977a75a33 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 56c85143-19cd-46b0-b9e5-1ba977a75a33',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '环境：Dev，IP：121.36.65.210',
        'hiGroup': null,
        'executorCount': 100,
        'sendEmail': null,
        'type': 2,
        'uuid': '56c85143-19cd-46b0-b9e5-1ba977a75a33',
        'createTime': '2021-01-07 08:02:48',
        'name': '121.36.65.210',
    }, {
        'labelId': 24,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t a2b208fe-3386-4b07-ae37-5c9201ef015e >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t a2b208fe-3386-4b07-ae37-5c9201ef015e',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'pipe流水线',
        'hiGroup': null,
        'executorCount': 1,
        'sendEmail': null,
        'type': 2,
        'uuid': 'a2b208fe-3386-4b07-ae37-5c9201ef015e',
        'createTime': '2020-12-29 06:00:37',
        'name': 'gitee-one-develop-1',
    }, {
        'labelId': 20,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 329d248a-2ebd-4a03-835e-432463978660 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 329d248a-2ebd-4a03-835e-432463978660',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': '69%',
        'memoryUsedRate': '77%',
        'status': 'ONLINE',
        'note': '80.97-Agent',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '329d248a-2ebd-4a03-835e-432463978660',
        'createTime': '2020-12-23 13:18:45',
        'name': '镜像发布专属',
    }, {
        'labelId': 19,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 04edf4f1-f6bf-4394-b0c0-dcecd1b76f86 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 04edf4f1-f6bf-4394-b0c0-dcecd1b76f86',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'iscan-parser\niscan-es',
        'hiGroup': null,
        'executorCount': 50,
        'sendEmail': null,
        'type': 2,
        'uuid': '04edf4f1-f6bf-4394-b0c0-dcecd1b76f86',
        'createTime': '2020-12-11 03:14:15',
        'name': '海关主机2-233',
    }, {
        'labelId': 19,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 9863156f-5750-4786-8861-2cb2a5d372f2 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 9863156f-5750-4786-8861-2cb2a5d372f2',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        // eslint-disable-next-line max-len
        'note': 'iscan-frontend\niScan-codestyle\nxref-iscan\niscan-server\niscan-server-export\niscan-miserver\niscan-scanner',
        'hiGroup': null,
        'executorCount': 50,
        'sendEmail': null,
        'type': 2,
        'uuid': '9863156f-5750-4786-8861-2cb2a5d372f2',
        'createTime': '2020-12-08 09:31:12',
        'name': '海关主机1-248',
    }, {
        'labelId': 13,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 8ad3c9f2-e2d3-4df6-9525-0ed8d6213736 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 8ad3c9f2-e2d3-4df6-9525-0ed8d6213736',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 5,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': '/home/work/pipline 8C32G，100G硬盘',
        'hiGroup': null,
        'executorCount': 8,
        'sendEmail': null,
        'type': 2,
        'uuid': '8ad3c9f2-e2d3-4df6-9525-0ed8d6213736',
        'createTime': '2020-11-11 07:38:56',
        'name': 'PipelineAgent',
    }, {
        'labelId': 17,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 818b0df4-374f-4223-9387-3d9daf6a3fa2 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 818b0df4-374f-4223-9387-3d9daf6a3fa2',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.6',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'cdsaljcaskljd',
        'hiGroup': null,
        'executorCount': 23,
        'sendEmail': null,
        'type': 2,
        'uuid': '818b0df4-374f-4223-9387-3d9daf6a3fa2',
        'createTime': '2020-10-29 11:08:10',
        'name': 'cjhkladslk',
    }, {
        'labelId': 16,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t ff7f7170-c594-4afc-9c12-e3b9481aee3a >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t ff7f7170-c594-4afc-9c12-e3b9481aee3a',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'csd',
        'hiGroup': null,
        'executorCount': 2,
        'sendEmail': null,
        'type': 2,
        'uuid': 'ff7f7170-c594-4afc-9c12-e3b9481aee3a',
        'createTime': '2020-10-22 12:24:15',
        'name': 'ksksk',
    }, {
        'labelId': 15,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t a9444692-1a73-4b1f-b2a4-15273b5fe393 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t a9444692-1a73-4b1f-b2a4-15273b5fe393',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'test',
        'hiGroup': null,
        'executorCount': 2,
        'sendEmail': null,
        'type': 2,
        'uuid': 'a9444692-1a73-4b1f-b2a4-15273b5fe393',
        'createTime': '2020-09-23 08:05:32',
        'name': 'testmachine',
    }, {
        'labelId': 13,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 94950676-02b8-4a71-857d-1fe147269b83 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 94950676-02b8-4a71-857d-1fe147269b83',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'agent目录是/osc-agent，密码是POCcc@2020',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '94950676-02b8-4a71-857d-1fe147269b83',
        'createTime': '2020-09-22 05:35:49',
        'name': '192.168.80.170-nwp',
    }, {
        'labelId': 14,
        'jarDownload': 'wget -O agent.jar http://osc.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s http://osc.gitee.work/sa_server -t 6f9cf702-ad42-4cd3-b079-31094f647b29 >> run.log 2>&1 &',
        'startShell': 'curl -s http://osc.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u http://osc.gitee.work/sa_server -t 6f9cf702-ad42-4cd3-b079-31094f647b29',
        'origin': 'SELF',
        'serverArg': 'http://osc.gitee.work',
        'jarUrl': 'http://osc.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'status': 'OFFLINE',
        'note': 'uat环境部署主机',
        'hiGroup': null,
        'executorCount': 2,
        'sendEmail': null,
        'type': 2,
        'uuid': '6f9cf702-ad42-4cd3-b079-31094f647b29',
        'createTime': '2020-09-03 10:40:33',
        'name': 'deployment_192.168.80.50',
    }];

export const labels = [
    {
        'id': 100079,
        'name': '1azewrer',
        'displayName': 'test',
        'createTime': '2022-02-22 14:54:45',
        'deleteStatus': false,
        'description': '',
        'purpose': 1,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 1,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 100009,
        'name': 'yxc_test',
        'displayName': 'yxc-test',
        'createTime': '2021-10-15 14:26:21',
        'deleteStatus': false,
        'description': 'yxc-test13',
        'purpose': 1,
        'type': 2,
        'agentEntities': null,
        'groupName': 'iPipe',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 2,
        'labelType': 1,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 187,
        'name': 'windows222222',
        'displayName': 'windows',
        'createTime': '2021-09-27 22:04:40',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'iPipe',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 2,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 165,
        'name': 'QAautest_linux',
        'displayName': 'QAautest_linux修改后',
        'createTime': '2021-09-27 21:33:15',
        'deleteStatus': true,
        'description': 'QAautest_linux修改后',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'iPipe',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 2,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 163,
        'name': 'QAautest_linux2',
        'displayName': 'QAautest_linux2',
        'createTime': '2021-09-27 21:20:31',
        'deleteStatus': true,
        'description': 'QAautest_linux',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'iPipe',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 2,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 161,
        'name': 'cqtest',
        'displayName': 'cqtest22',
        'createTime': '2021-09-27 21:06:00',
        'deleteStatus': false,
        'description': '2',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'iPipe',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 2,
        'labelType': 3,
        'registerAgentNum': 6,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 139,
        'name': 'testpf11',
        'displayName': 'testpf11',
        'createTime': '2021-09-24 11:17:22',
        'deleteStatus': true,
        'description': '',
        'purpose': 1,
        'type': 2,
        'agentEntities': null,
        'groupName': 'iPipe',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 2,
        'labelType': 1,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 107,
        'name': 'GiteeGo',
        'displayName': '公有云测试机-勿动',
        'createTime': '2021-08-30 09:18:54',
        'deleteStatus': false,
        'description': '公有云测试机',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 103,
        'name': 'ArmJiraIdentify',
        'displayName': 'ArmJira',
        'createTime': '2021-08-16 13:31:36',
        'deleteStatus': false,
        'description': 'ArmJira',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 2,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 97,
        'name': 'code',
        'displayName': 'Code',
        'createTime': '2021-06-28 06:17:43',
        'deleteStatus': false,
        'description': '',
        'purpose': 1,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 1,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 95,
        'name': 'Compose_Agent',
        'displayName': 'Compose_Agent',
        'createTime': '2021-05-26 06:54:39',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 79,
        'name': 'one',
        'displayName': 'One',
        'createTime': '2021-04-16 03:11:49',
        'deleteStatus': false,
        'description': 'One团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 77,
        'name': 'doc',
        'displayName': 'Doc',
        'createTime': '2021-04-16 03:11:14',
        'deleteStatus': false,
        'description': 'Doc团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 75,
        'name': 'newproject',
        'displayName': 'NewProject',
        'createTime': '2021-04-16 03:11:00',
        'deleteStatus': false,
        'description': '新Project团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 73,
        'name': 'codego',
        'displayName': 'CodeGo',
        'createTime': '2021-04-16 03:10:33',
        'deleteStatus': false,
        'description': 'Code Go团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 71,
        'name': 'coderuby',
        'displayName': 'CodeRuby',
        'createTime': '2021-04-16 03:10:13',
        'deleteStatus': false,
        'description': 'Code Ruby团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 67,
        'name': 'scan',
        'displayName': 'Scan',
        'createTime': '2021-04-16 03:09:19',
        'deleteStatus': false,
        'description': 'Scan团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 65,
        'name': 'pipe',
        'displayName': 'Pipe',
        'createTime': '2021-04-16 03:09:03',
        'deleteStatus': false,
        'description': 'Pipe团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 63,
        'name': 'project',
        'displayName': 'Project',
        'createTime': '2021-04-16 03:03:17',
        'deleteStatus': false,
        'description': 'Project团队专属',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 51,
        'name': 'proxima',
        'displayName': 'proxima',
        'createTime': '2021-03-26 12:38:18',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 49,
        'name': 'yishoubao',
        'displayName': '易收宝项目组',
        'createTime': '2021-03-25 03:15:58',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 45,
        'name': 'xhd_test_1',
        'displayName': 'xhd_test_1',
        'createTime': '2021-03-08 06:35:36',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 40,
        'name': 'test',
        'displayName': 'uat-test',
        'createTime': '2021-01-28 09:50:23',
        'deleteStatus': false,
        'description': 'uat-test',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 1,
        'oldDisplayName': null,
    }, {
        'id': 32,
        'name': 'GiteePipeDemo',
        'displayName': 'GiteePipeDemo',
        'createTime': '2021-01-12 06:16:30',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 1,
        'oldDisplayName': null,
    }, {
        'id': 28,
        'name': 'pipe_servergroup_demo',
        'displayName': 'GiteePipe-主机组示例',
        'createTime': '2021-01-07 08:02:05',
        'deleteStatus': false,
        'description': 'Gitee Pipe 主机组示例（请勿删除，请勿使用）',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 24,
        'name': 'one_test',
        'displayName': 'giteeone主机组',
        'createTime': '2020-12-29 06:00:10',
        'deleteStatus': false,
        'description': 'pipe流水线',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 20,
        'name': 'pipeline_work',
        'displayName': 'Pipeline-工作主机-勿动',
        'createTime': '2020-12-23 13:17:44',
        'deleteStatus': false,
        'description': '用于流水线配置任务主机《《《勿动》》》',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 1,
        'oldDisplayName': null,
    }, {
        'id': 19,
        'name': '180.76.135.248',
        'displayName': 'Scan海关环境主机组',
        'createTime': '2020-12-08 09:30:10',
        'deleteStatus': false,
        'description': 'Scan海关环境主机组-勿删！',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 2,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 17,
        'name': 'zhangyng',
        'displayName': 'zhangyng',
        'createTime': '2020-10-29 11:07:56',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 16,
        'name': 'work',
        'displayName': 'work',
        'createTime': '2020-10-22 12:23:47',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 15,
        'name': 'waltertest',
        'displayName': 'waltertest',
        'createTime': '2020-09-23 08:04:58',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 14,
        'name': 'osc_agent',
        'displayName': '非生产环境部署主机组',
        'createTime': '2020-09-03 10:39:26',
        'deleteStatus': false,
        'description': 'UAT/DEV部署主机   ***  误删  ***',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 2,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 13,
        'name': 'agent',
        'displayName': 'pipline',
        'createTime': '2020-08-25 06:29:22',
        'deleteStatus': false,
        'description': 'pipline-agent',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'xly-poc',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 2,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 99999,
        'name': 'IDE',
        'displayName': 'cloudIde',
        'createTime': '1970-01-01 00:00:00',
        'deleteStatus': false,
        'description': 'IDE主机组',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': null,
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': null,
        'labelType': 3,
        'registerAgentNum': 24,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 1,
        'name': 'cloudIde',
        'displayName': 'cloudIde',
        'createTime': '1970-01-01 00:00:00',
        'deleteStatus': true,
        'description': 'cloudIde主机',
        'purpose': 3,
        'type': 2,
        'agentEntities': null,
        'groupName': 'ide',
        'origin': 'SELF',
        'authorizeProjects': null,
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 40,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }];







