export const GET_USER_FROM_ONE_S = Symbol('GET_USER_FROM_ONE_S');
export const GET_EXECUTION_DETAIL_S = Symbol('GET_EXECUTION_DETAIL_S');
export const GET_NOAH_LIST_S = Symbol('GET_NOAH_LIST_S');
export const GET_NOAH_DETAIL_S = Symbol('GET_NOAH_DETAIL_S');
export const UPDATE_CATEGORY_LIST_S = Symbol('UPDATE_CATEGORY_LIST_S');
export const UPDATE_DISK_SPACE_INFO_S = Symbol('UPDATE_DISK_SPACE_INFO_S');
