export const UPDATE_USER_FROM_ONE_S = 'UPDATE_USER_FROM_ONE_S';
export const GET_EXECUTION_DETAIL_S = 'GET_EXECUTION_DETAIL_S';
export const GET_NOAH_LIST_S = 'GET_NOAH_LIST_S';
export const GET_NOAH_DETAIL_S = 'GET_NOAH_DETAIL_S';
export const UPDATE_CATEGORY_LIST_S = 'UPDATE_CATEGORY_LIST_S';
export const UPDATE_DISK_SPACE_INFO_S = 'UPDATE_DISK_SPACE_INFO_S';
export const UPDATE_CURRENT_USER_S = 'UPDATE_CURRENT_USER_S';
